CREATE TABLE `tipo_curso` (
  `cod_tip_cur` int(11) NOT NULL PRIMARY KEY AUTO_INCREMENT COMMENT 'Código del Tipo de Curso. Autoincremental',
  `nom_tip_cur` varchar(50) NOT NULL COMMENT 'Nombre del tipo de curso',
  `fky_usu_onl` int(11) NOT NULL COMMENT 'Código del profesor',
  `hor_tip_cur` int(11) NOT NULL COMMENT 'Numero de Horas Académicas',
  `can_tip_cur` int(11) NOT NULL COMMENT 'Cantidad de clases del curso',
  `cer_tip_cur` varchar(50) NOT NULL COMMENT 'Nombre que aparecerá en el certificado',
  `des_tip_cur` text NOT NULL COMMENT 'Sirve para aclarar de qué se trata el curso.',
  `dir_tip_cur` varchar(80) NOT NULL COMMENT 'Curso Dirigido a?',
  `cla_tip_cur` int(11) NOT NULL COMMENT 'Cantidad de Clases',
  `obj_tip_cur` varchar(255) NOT NULL COMMENT 'Objetivo del Curso',
  `min_tip_cur` int(11) NOT NULL COMMENT 'Número mínimo de cupos',
  `max_tip_cur` int(11) NOT NULL COMMENT 'Numero maximo de cupos',
  `ava_tip_cur` char(1) NOT NULL COMMENT 'Valores: A: Certificado Avalado por el Ministerio de Educación N: Certificado No Avalado por el Ministerio de Educación',
  `mat_tip_cur` text DEFAULT NULL COMMENT 'URL del material del curso comprimido en un .zip',
  `con_tip_cur` text DEFAULT NULL COMMENT 'URL del contenido del curso',
  `ico_tip_cur` text NOT NULL COMMENT 'Icono del Curso',
  `car_tip_cur` text NOT NULL COMMENT 'Foto de la Card',
  `sli_tip_cur` text NOT NULL COMMENT 'Foto del Slider',
  `cao_tip_cur` text NOT NULL COMMENT 'URL para card de cursos online',
  `arc_tip_cur` text DEFAULT NULL COMMENT 'URL del material completo del curso online',
  `vid_tip_cur` text DEFAULT NULL COMMENT 'Video promocional del curso online',
  `fky_area` int(11) NOT NULL COMMENT 'Area a la que pertenece el curso: - Diseño Gráfico - Informática - Arquitectura - Comunicación Social',
  `fky_empresa` int(11) NOT NULL COMMENT 'Empresa que organiza el curso',
  `was_tip_cur` text DEFAULT NULL COMMENT 'URL del grupo de Whatsapp del Curso',
  `est_tip_cur` char(1) NOT NULL COMMENT 'Valores: A: Activo I: Inactivo'
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='Guarda los datos generales de los diferentes cursos que impa';
